### ISSUE TITLE
integratio not working after upating to 2023.5

### ISSUE THREAD

**Issue by gazelle-hub** [zacharyrs/ha-melview#22]
I'm getting the following error in HA after upgrading to 2023.5.2 (it wqas working fine on 2022.4.5).

I get the following error log:

Logger: homeassistant.config_entries
Source: custom_components/melview/__init__.py:93
Integration: MelView ([documentation](https://github.com/haggis663/ha-melview), [issues](https://github.com/haggis663/ha-melview/issues))
First occurred: May 11, 2023 at 10:05:56 PM (2 occurrences)
Last logged: 5:16:12 PM

Error setting up entry adamjameshay@gmail.com for melview
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/melview/__init__.py", line 93, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by gazelle-hub** [comment]
I've rolled back to 2023.4.1 and it is working.
